version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: MySafeNote.Server/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Port=5432;Database=mysafenotedb;Username=admin;Password=12345678;Pooling=true;Timeout=30;CommandTimeout=30
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine  # Более легкая и стабильная версия
    restart: always
    environment:
      POSTGRES_DB: mysafenotedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_HOST_AUTH_METHOD: trust  # Для упрощения подключения в dev-режиме
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Для внешнего подключения при необходимости
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mysafenotedb"]
      interval: 5s
      timeout: 5s
      retries: 10
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pgdata: